name: Publish to Pypi

on:
  release:
      types: [published]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - run: poetry publish --build --username __token__ --password $PYPI_API_TOKEN
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
